      - name: Azure Login
        uses: azure/login@v1
        with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
      - name: Checkout
        uses: actions/checkout@v1
      
      - uses: azure/arm-deploy@v1
        with:
            resourceGroupName: github-action-arm-rg
            template: azuredeploy.json
            parameters: azuredeploy.parameters.json
            subscriptionId: b5ba36b7-2efd-4b2a-9789-9449399ab382
