# This is a basic workflow to help you get started with Actions

name: AzureRead

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true
        
    - name: Azure CLI Action
      uses: Azure/cli@1.0.4
      with:
        # Specify the script here
        inlineScript: 
          az account subscription list 
