# This is a basic workflow to help you get started with Actions

name: AzureRead

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Azure CLI script
      uses: azure/CLI@v1
      id: 'accountinfo'
      with:
        azcliversion: 2.0.72
        inlineScript: |
          az account show --subscription 'b5ba36b7-2efd-4b2a-9789-9449399ab382'
          
    - name: Print accountinfo
      run: echo '${{ steps.accountinfo.outputs }}'
