# This is a basic workflow to help you get started with Actions

name: array

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Create list from array of strings
        uses: lucaspinheirogit/list-from-string-array-action@v1.4.3
        with:
          stringArray: '["file1","file2","file3"]'
          
      - uses: actions/checkout@v2
        
      - name: Get modified files
        id: modified_files
        uses: trilom/file-changes-action@v1.0.0
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Create list of modified files
        id: modified_files_list
        uses: lucaspinheirogit/list-from-string-array-action@v1.4.3
        with:
          stringArray: ${{ steps.modified_files.outputs.files_modified }}
      - name: Print modified files
        run: echo '${{ steps.modified_files_list.outputs.stringList }}'

