
# This is a basic workflow to help you get started with Actions

name: VMCreation

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Checkout
      uses: actions/checkout@v1
      
    - uses: azure/arm-deploy@v1
      with:
         resourceGroupName: github-action-arm-rg
         template: ./azuredeploy.json
         parameters: ./azuredeploy.parameters.json
