
# This is a basic workflow to help you get started with Actions

name: VMCreation

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Checkout
      uses: actions/checkout@v1
      
    - name: Azure ARM Deployment
      uses: azure/ARM@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
          az group create --location "Central India" --name "DemoVM"
          az group deployment create --resource-group "DemoVM" --template-file "$GITHUB_WORKSPACE/azuredeploy.json" --parameters "$GITHUB_WORKSPACE/azuredeploy.parameters.json"
